[features]
seeds = false
skip-lint = false

[programs.localnet]
fizzcaps_onchain = "GDGexnGtZPoD1aHv6qg8hjeSspujwWnxJCtdrrj2gKpP"  # Will replace after first build

[programs.devnet]
fizzcaps_onchain = "ReplaceWithDevnetIDAfterDeploy"

[programs.mainnet-beta]
fizzcaps_onchain = "ReplaceWithMainnetIDAfterDeploy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn install && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
